import { Countries } from "./countries";
import { Title } from "./title";

export const AllForms = {
  "Confirm Details": [
    {
      label: "First Name",
      id: "firstName",
      placeholder: "Jane",
      type: "text",
      error: "",
      isRequired: true,
      isHalfWidth: true,
      hasMarginRight: true,
      isDisabled: true,
    },
    {
      label: "Last Name",
      id: "lastName",
      placeholder: "Doe",
      type: "text",
      error: "",
      isRequired: true,
      isHalfWidth: true,
      isDisabled: true,
    },
    {
      label: "Date of Birth",
      id: "dateOfBirth",
      placeholder: "Choose date",
      type: "date",
      error: "",
      isRequired: true,
      isHalfWidth: true,
      hasMarginRight: true,
      isDisabled: true,
    },
    {
      label: "Email",
      id: "email",
      placeholder: "user@email.com",
      type: "email",
      error: "",
      isRequired: true,
      isHalfWidth: true,
    },
    {
      label: "Phone Number",
      id: "phone",
      placeholder: "0123456789",
      type: "number",
      error: "",
      isRequired: true,
      isHalfWidth: true,
      hasMarginRight: true,
    },
    {
      label: "Gender",
      id: "gender",
      placeholder: "Male",
      type: "text",
      error: "",
      isRequired: true,
      isHalfWidth: true,
      isDropDown: true,
      list: [
        { key: "Male", value: "Male" },
        { key: "Female", value: "Female" },
      ],
    },
    {
      label: "Title",
      id: "title",
      placeholder: "Mr.",
      type: "text",
      error: "",
      isRequired: true,
      isHalfWidth: true,
      hasMarginRight: true,
      list: Title.map((t) => ({ key: t.label, value: t.value })),
      isDropDown: true,
    },
    {
      label: "Marital Status",
      id: "maritalStatus",
      placeholder: "Single",
      type: "text",
      error: "",
      isRequired: true,
      isHalfWidth: true,
      isDropDown: true,
      list: [
        { key: "Single", value: "Single" },
        { key: "Married", value: "Married" },
        { key: "Divorced", value: "Divorced" },
        { key: "Widowed", value: "Widowed" },
      ],
    },
    {
      label: "Nationality",
      id: "nationality",
      placeholder: "Nigerian",
      type: "text",
      error: "",
      isRequired: true,
      isDropDown: true,
      list: Countries.map((t) => ({ key: t.value, value: t.value })),
    },
    {
      label: "Residential Address",
      id: "residentialAddress",
      placeholder: "123 Street",
      type: "text",
      error: "",
      isRequired: true,
    },
  ],
  "Personal Account": [
    {
      label: "Email",
      id: "email",
      placeholder: "user@email.com",
      type: "email",
      error: "",
      isRequired: true,
    },
    {
      label: "BVN",
      id: "bvn",
      placeholder: "e.g 123456789",
      type: "number",
      error: "",
      isRequired: true,
    },
    {
      label: "Date of Birth",
      id: "dateOfBirth",
      placeholder: "Choose date",
      type: "date",
      error: "",
      isRequired: true,
    },
    {
      label: "Referral Code",
      id: "refCode",
      placeholder: "0000",
      type: "text",
      error: "",
      isRequired: false,
    },
  ],
  "Optimus Natives": [
    {
      label: "Email -  Natives",
      id: "email",
      placeholder: "user@email.com",
      type: "email",
      error: "",
      isRequired: true,
    },
    {
      label: "BVN",
      id: "bvn",
      placeholder: "e.g 123456789",
      type: "number",
      error: "",
      isRequired: true,
    },
    {
      label: "Date of Birth",
      id: "dateOfBirth",
      placeholder: "Choose date",
      type: "date",
      error: "",
      isRequired: true,
    },
    {
      label: "Referral Code",
      id: "refcode",
      placeholder: "user@email.com",
      type: "email",
      error: "",
      isRequired: false,
    },
  ],
  "Optimus One23": [
    {
      label: "Email - One 23",
      id: "email",
      placeholder: "user@email.com",
      type: "email",
      error: "",
      isRequired: true,
    },
    {
      label: "BVN",
      id: "bvn",
      placeholder: "e.g 123456789",
      type: "number",
      error: "",
      isRequired: true,
    },
    {
      label: "Date of Birth",
      id: "dateOfBirth",
      placeholder: "Choose date",
      type: "date",
      error: "",
      isRequired: true,
    },
    {
      label: "Referral Code",
      id: "refcode",
      placeholder: "user@email.com",
      type: "email",
      error: "",
      isRequired: false,
    },
  ],
  Edge: [
    {
      label: "Email - Edge",
      id: "email",
      placeholder: "user@email.com",
      type: "email",
      error: "",
      isRequired: true,
    },
    {
      label: "BVN",
      id: "bvn",
      placeholder: "e.g 123456789",
      type: "number",
      error: "",
      isRequired: true,
    },
    {
      label: "Date of Birth",
      id: "dateOfBirth",
      placeholder: "Choose date",
      type: "date",
      error: "",
      isRequired: true,
    },
    {
      label: "Referral Code",
      id: "refcode",
      placeholder: "user@email.com",
      type: "email",
      error: "",
      isRequired: false,
    },
  ],
  "Account Number": [
    {
      label: "Account Number",
      id: "accNo",
      placeholder: "e.g 123456789",
      type: "number",
      error: "",
      isRequired: true,
    },
    {
      label: "Date of Birth",
      id: "dateOfBirth",
      placeholder: "Choose date",
      type: "date",
      error: "",
      isRequired: true,
    },
  ],
  Token: [
    {
      label: "Account Number",
      id: "accNo",
      placeholder: "e.g 123456789",
      type: "number",
      error: "",
      isRequired: true,
    },
    {
      label: "Token",
      id: "token",
      placeholder: "Enter token",
      type: "text",
      error: "",
      isRequired: true,
    },
  ],
  "Debit Card": [
    {
      label: "Account Number",
      id: "accNo",
      placeholder: "e.g 123456789",
      type: "number",
      error: "",
      isRequired: true,
    },
    {
      label: "First 6 Digits",
      id: "firstdigits",
      placeholder: "e.g 123456",
      type: "number",
      error: "",
      isRequired: true,
      isHalfWidth: true,
      hasMarginRight: true,
    },
    {
      label: "Last 4 Digits",
      id: "lastdigits",
      placeholder: "e.g 123456",
      type: "number",
      error: "",
      isRequired: true,
      isHalfWidth: true,
    },
    {
      label: "Card PIN",
      id: "cardpin",
      placeholder: "Enter your 4-digit card PIN",
      type: "number",
      error: "",
      isRequired: true,
    },
  ],
};

export const CreateCredentials = [
  {
    label: "Create a Password",
    id: "createPassword",
    placeholder: "Password",
    type: "password",
    error: "",
    isRequired: true,
  },
  {
    label: "Confirm Password",
    id: "confirmPassword",
    placeholder: "Re-enter password",
    type: "password",
    error: "",
    isRequired: true,
  },
  {
    label: "Create Transaction PIN",
    id: "createPin",
    placeholder: "Enter a 4-digit PIN",
    type: "number",
    error: "",
    isRequired: true,
  },
  {
    label: "Confirm Transaction PIN",
    id: "confirmPin",
    placeholder: "Confirm 4-digit PIN",
    type: "number",
    error: "",
    isRequired: true,
  },



];

export const AccountProductIds = {
  "Personal Account": "SD-I/1",
  "Optimus Natives": "OPTI-NATI_1/11",
  "Optimus One23": "OPTI-NATI_1/11",
  "Optimus Sage": "OP-WAZ_1/15",
  "Optimus Avanzar": "OPT_AVZ/22",
  Edge: "OPTI-NATI_1/11",
};
