import airtime from "../../public/assets/images/airtimeIcon.svg";
import cableTV from "../../public/assets/images/cableTVIcon.svg";
import dice from "../../public/assets/images/dice.svg";
import lasgIcon from "../../public/assets/images/lasgIcon.svg";

export const Category = [
  {
    id: "1",
    name: "Aid,Grants and Donations",
    src: cableTV,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "2",
    name: "Airtime Top-up",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "3",
    name: "Associations and Societies",
    src: cableTV,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "4",
    name: "BankOne MFBs",
    src: dice,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "5",
    name: "CableTV",
    src: cableTV,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "6",
    name: "Commerce Retail Trade",
    src: dice,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "7",
    name: "Credit and Loans",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "8",
    name: "Cross River State Govt",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "9",
    name: "Dealer Payments",
    src: cableTV,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "10",
    name: "Embassies",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "11",
    name: "Eminent Technologies",
    src: cableTV,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "12",
    name: "Event Tickets",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "13",
    name: "Financial Services",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "14",
    name: "Government Payments",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "15",
    name: "InsureDirect",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "16",
    name: "International Airtime",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "17",
    name: "Internet Services",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "18",
    name: "Interswitch Services",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "19",
    name: "Merchant Payments",
    src: lasgIcon,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "20",
    name: "Merchant Services",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "21",
    name: "Mobile Money Wallets",
    src: lasgIcon,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "22",
    name: "Mobile Recharge",
    src: dice,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "23",
    name: "Nestle Distributors",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "24",
    name: "Online Shopping",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "25",
    name: "Pay TV",
    src: lasgIcon,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "26",
    name: "PayChoice",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "27",
    name: "Prepaid Card Services",
    src: lasgIcon,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "28",
    name: "Products and Services",
    src: dice,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "29",
    name: "Religious Institutions",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "30",
    name: "School and Exam Fees",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "31",
    name: "Send and Receive Money",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "32",
    name: "Shopping",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "33",
    name: "Sports and Gaming",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "34",
    name: "Transport and Toll Payments",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "35",
    name: "Travel and Hotel",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "36",
    name: "Utilities",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "37",
    name: "Underwater Services",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "38",
    name: "Vatican City",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  {
    id: "39",
    name: "Water Services",
    src: airtime,
    description: "Enjoy high-quality channels with our cable TV services.",
  },
  { id: "40", name: "Zoo" ,    description: "Enjoy high-quality channels with our cable TV services.",
	},
];

