
export const CountriesCode =  [
  { value: " (+93) Afghanistan", code: "AF", dial_code: "+93" },
  { value: " (+355) Albania", code: "AL", dial_code: "+355" },
  { value: " (+213) Algeria", code: "DZ", dial_code: "+213" },
  { value: " (+1-684) American Samoa", code: "AS", dial_code: "+1-684" },
  { value: " (+376) Andorra", code: "AD", dial_code: "+376" },
  { value: " (+244) Angola", code: "AO", dial_code: "+244" },
  { value: " (+1-264) Anguilla", code: "AI", dial_code: "+1-264" },
  { value: " (+1-268) Antigua and Barbuda", code: "AG", dial_code: "+1-268" },
  { value: " (+54) Argentina", code: "AR", dial_code: "+54" },
  { value: " (+374) Armenia", code: "AM", dial_code: "+374" },
  { value: " (+297) Aruba", code: "AW", dial_code: "+297" },
  { value: " (+61) Australia", code: "AU", dial_code: "+61" },
  { value: " (+43) Austria", code: "AT", dial_code: "+43" },
  { value: " (+994) Azerbaijan", code: "AZ", dial_code: "+994" },
  { value: " (+1-242) Bahamas", code: "BS", dial_code: "+1-242" },
  { value: " (+973) Bahrain", code: "BH", dial_code: "+973" },
  { value: " (+880) Bangladesh", code: "BD", dial_code: "+880" },
  { value: " (+1-246) Barbados", code: "BB", dial_code: "+1-246" },
  { value: " (+375) Belarus", code: "BY", dial_code: "+375" },
  { value: " (+32) Belgium", code: "BE", dial_code: "+32" },
  { value: " (+501) Belize", code: "BZ", dial_code: "+501" },
  { value: " (+229) Benin", code: "BJ", dial_code: "+229" },
  { value: " (+1-441) Bermuda", code: "BM", dial_code: "+1-441" },
  { value: " (+975) Bhutan", code: "BT", dial_code: "+975" },
  { value: " (+591) Bolivia", code: "BO", dial_code: "+591" },
  { value: " (+387) Bosnia and Herzegovina", code: "BA", dial_code: "+387" },
  { value: " (+267) Botswana", code: "BW", dial_code: "+267" },
  { value: " (+55) Brazil", code: "BR", dial_code: "+55" },
  { value: " (+246) British Indian Ocean Territory", code: "IO", dial_code: "+246" },
  { value: " (+1-284) British Virgin Islands", code: "VG", dial_code: "+1-284" },
  { value: " (+673) Brunei", code: "BN", dial_code: "+673" },
  { value: " (+359) Bulgaria", code: "BG", dial_code: "+359" },
  { value: " (+226) Burkina Faso", code: "BF", dial_code: "+226" },
  { value: " (+257) Burundi", code: "BI", dial_code: "+257" },
  { value: " (+855) Cambodia", code: "KH", dial_code: "+855" },
  { value: " (+237) Cameroon", code: "CM", dial_code: "+237" },
  { value: " (+1) Canada", code: "CA", dial_code: "+1" },
  { value: " (+238) Cape Verde", code: "CV", dial_code: "+238" },
  { value: " (+1-345) Cayman Islands", code: "KY", dial_code: "+1-345" },
  { value: " (+236) Central African Republic", code: "CF", dial_code: "+236" },
  { value: " (+235) Chad", code: "TD", dial_code: "+235" },
  { value: " (+56) Chile", code: "CL", dial_code: "+56" },
  { value: " (+86) China", code: "CN", dial_code: "+86" },
  { value: " (+61) Christmas Island", code: "CX", dial_code: "+61" },
  { value: " (+61) Cocos Islands", code: "CC", dial_code: "+61" },
  { value: " (+57) Colombia", code: "CO", dial_code: "+57" },
  { value: " (+269) Comoros", code: "KM", dial_code: "+269" },
  { value: " (+682) Cook Islands", code: "CK", dial_code: "+682" },
  { value: " (+506) Costa Rica", code: "CR", dial_code: "+506" },
  { value: " (+385) Croatia", code: "HR", dial_code: "+385" },
  { value: " (+53) Cuba", code: "CU", dial_code: "+53" },
  { value: " (+599) Curacao", code: "CW", dial_code: "+599" },
  { value: " (+357) Cyprus", code: "CY", dial_code: "+357" },
  { value: " (+420) Czech Republic", code: "CZ", dial_code: "+420" },
  { value: " (+243) Democratic Republic of the Congo", code: "CD", dial_code: "+243" },
  { value: " (+45) Denmark", code: "DK", dial_code: "+45" },
  { value: " (+253) Djibouti", code: "DJ", dial_code: "+253" },
  { value: " (+1-767) Dominica", code: "DM", dial_code: "+1-767" },
  { value: " (+1-809, 1-829, 1-849) Dominican Republic", code: "DO", dial_code: "+1-809" },
  { value: " (+670) East Timor", code: "TL", dial_code: "+670" },
  { value: " (+593) Ecuador", code: "EC", dial_code: "+593" },
  { value: " (+20) Egypt", code: "EG", dial_code: "+20" },
  { value: " (+503) El Salvador", code: "SV", dial_code: "+503" },
  { value: " (+240) Equatorial Guinea", code: "GQ", dial_code: "+240" },
  { value: " (+291) Eritrea", code: "ER", dial_code: "+291" },
  { value: " (+372) Estonia", code: "EE", dial_code: "+372" },
  { value: " (+251) Ethiopia", code: "ET", dial_code: "+251" },
  { value: " (+500) Falkland Islands", code: "FK", dial_code: "+500" },
  { value: " (+298) Faroe Islands", code: "FO", dial_code: "+298" },
  { value: " (+679) Fiji", code: "FJ", dial_code: "+679" },
  { value: " (+358) Finland", code: "FI", dial_code: "+358" },
  { value: " (+33) France", code: "FR", dial_code: "+33" },
  { value: " (+594) French Guiana", code: "GF", dial_code: "+594" },
  { value: " (+689) French Polynesia", code: "PF", dial_code: "+689" },
  { value: " (+241) Gabon", code: "GA", dial_code: "+241" },
  { value: " (+220) Gambia", code: "GM", dial_code: "+220" },
  { value: " (+995) Georgia", code: "GE", dial_code: "+995" },
  { value: " (+49) Germany", code: "DE", dial_code: "+49" },
  { value: " (+233) Ghana", code: "GH", dial_code: "+233" },
  { value: " (+350) Gibraltar", code: "GI", dial_code: "+350" },
  { value: " (+30) Greece", code: "GR", dial_code: "+30" },
  { value: " (+299) Greenland", code: "GL", dial_code: "+299" },
  { value: " (+1-473) Grenada", code: "GD", dial_code: "+1-473" },
  { value: " (+590) Guadeloupe", code: "GP", dial_code: "+590" },
  { value: " (+1-671) Guam", code: "GU", dial_code: "+1-671" },
  { value: " (+502) Guatemala", code: "GT", dial_code: "+502" },
  { value: " (+44-1481) Guernsey", code: "GG", dial_code: "+44-1481" },
  { value: " (+224) Guinea", code: "GN", dial_code: "+224" },
  { value: " (+245) Guinea-Bissau", code: "GW", dial_code: "+245" },
  { value: " (+592) Guyana", code: "GY", dial_code: "+592" },
  { value: " (+509) Haiti", code: "HT", dial_code: "+509" },
  { value: " (+504) Honduras", code: "HN", dial_code: "+504" },
  { value: " (+852) Hong Kong", code: "HK", dial_code: "+852" },
  { value: " (+36) Hungary", code: "HU", dial_code: "+36" },
  { value: " (+354) Iceland", code: "IS", dial_code: "+354" },
  { value: " (+91) India", code: "IN", dial_code: "+91" },
  { value: " (+62) Indonesia", code: "ID", dial_code: "+62" },
  { value: " (+98) Iran", code: "IR", dial_code: "+98" },
  { value: " (+964) Iraq", code: "IQ", dial_code: "+964" },
  { value: " (+353) Ireland", code: "IE", dial_code: "+353" },
  { value: " (+44-1624) Isle of Man", code: "IM", dial_code: "+44-1624" },
  { value: " (+972) Israel", code: "IL", dial_code: "+972" },
  { value: " (+39) Italy", code: "IT", dial_code: "+39" },
  { value: " (+225) Ivory Coast", code: "CI", dial_code: "+225" },
  { value: " (+1-876) Jamaica", code: "JM", dial_code: "+1-876" },
  { value: " (+81) Japan", code: "JP", dial_code: "+81" },
  { value: " (+44-1534) Jersey", code: "JE", dial_code: "+44-1534" },
  { value: " (+962) Jordan", code: "JO", dial_code: "+962" },
  { value: " (+7) Kazakhstan", code: "KZ", dial_code: "+7" },
  { value: " (+254) Kenya", code: "KE", dial_code: "+254" },
  { value: " (+686) Kiribati", code: "KI", dial_code: "+686" },
  { value: " (+383) Kosovo", code: "XK", dial_code: "+383" },
  { value: " (+965) Kuwait", code: "KW", dial_code: "+965" },
  { value: " (+996) Kyrgyzstan", code: "KG", dial_code: "+996" },
  { value: " (+856) Laos", code: "LA", dial_code: "+856" },
  { value: " (+371) Latvia", code: "LV", dial_code: "+371" },
  { value: " (+961) Lebanon", code: "LB", dial_code: "+961" },
  { value: " (+266) Lesotho", code: "LS", dial_code: "+266" },
  { value: " (+231) Liberia", code: "LR", dial_code: "+231" },
  { value: " (+218) Libya", code: "LY", dial_code: "+218" },
  { value: " (+423) Liechtenstein", code: "LI", dial_code: "+423" },
  { value: " (+370) Lithuania", code: "LT", dial_code: "+370" },
  { value: " (+352) Luxembourg", code: "LU", dial_code: "+352" },
  { value: " (+853) Macau", code: "MO", dial_code: "+853" },
  { value: " (+389) Macedonia", code: "MK", dial_code: "+389" },
  { value: " (+261) Madagascar", code: "MG", dial_code: "+261" },
  { value: " (+265) Malawi", code: "MW", dial_code: "+265" },
  { value: " (+60) Malaysia", code: "MY", dial_code: "+60" },
  { value: " (+960) Maldives", code: "MV", dial_code: "+960" },
  { value: " (+223) Mali", code: "ML", dial_code: "+223" },
  { value: " (+356) Malta", code: "MT", dial_code: "+356" },
  { value: " (+692) Marshall Islands", code: "MH", dial_code: "+692" },
  { value: " (+596) Martinique", code: "MQ", dial_code: "+596" },
  { value: " (+222) Mauritania", code: "MR", dial_code: "+222" },
  { value: " (+230) Mauritius", code: "MU", dial_code: "+230" },
  { value: " (+262) Mayotte", code: "YT", dial_code: "+262" },
  { value: " (+52) Mexico", code: "MX", dial_code: "+52" },
  { value: " (+691) Micronesia", code: "FM", dial_code: "+691" },
  { value: " (+373) Moldova", code: "MD", dial_code: "+373" },
  { value: " (+377) Monaco", code: "MC", dial_code: "+377" },
  { value: " (+976) Mongolia", code: "MN", dial_code: "+976" },
  { value: " (+382) Montenegro", code: "ME", dial_code: "+382" },
  { value: " (+1-664) Montserrat", code: "MS", dial_code: "+1-664" },
  { value: " (+212) Morocco", code: "MA", dial_code: "+212" },
  { value: " (+258) Mozambique", code: "MZ", dial_code: "+258" },
  { value: " (+95) Myanmar", code: "MM", dial_code: "+95" },
  { value: " (+264) Namibia", code: "NA", dial_code: "+264" },
  { value: " (+674) Nauru", code: "NR", dial_code: "+674" },
  { value: " (+977) Nepal", code: "NP", dial_code: "+977" },
  { value: " (+31) Netherlands", code: "NL", dial_code: "+31" },
  { value: " (+599) Netherlands Antilles", code: "AN", dial_code: "+599" },
  { value: " (+687) New Caledonia", code: "NC", dial_code: "+687" },
  { value: " (+64) New Zealand", code: "NZ", dial_code: "+64" },
  { value: " (+505) Nicaragua", code: "NI", dial_code: "+505" },
  { value: " (+227) Niger", code: "NE", dial_code: "+227" },
  { value: " (+234) Nigeria", code: "NG", dial_code: "+234" },
  { value: " (+683) Niue", code: "NU", dial_code: "+683" },
  { value: " (+850) North Korea", code: "KP", dial_code: "+850" },
  { value: " (+1-670) Northern Mariana Islands", code: "MP", dial_code: "+1-670" },
  { value: " (+47) Norway", code: "NO", dial_code: "+47" },
  { value: " (+968) Oman", code: "OM", dial_code: "+968" },
  { value: " (+92) Pakistan", code: "PK", dial_code: "+92" },
  { value: " (+680) Palau", code: "PW", dial_code: "+680" },
  { value: " (+970) Palestine", code: "PS", dial_code: "+970" },
  { value: " (+507) Panama", code: "PA", dial_code: "+507" },
  { value: " (+675) Papua New Guinea", code: "PG", dial_code: "+675" },
  { value: " (+595) Paraguay", code: "PY", dial_code: "+595" },
  { value: " (+51) Peru", code: "PE", dial_code: "+51" },
  { value: " (+63) Philippines", code: "PH", dial_code: "+63" },
  { value: " (+64) Pitcairn", code: "PN", dial_code: "+64" },
  { value: " (+48) Poland", code: "PL", dial_code: "+48" },
  { value: " (+351) Portugal", code: "PT", dial_code: "+351" },
  { value: " (+1-787, 1-939) Puerto Rico", code: "PR", dial_code: "+1-787" },
  { value: " (+974) Qatar", code: "QA", dial_code: "+974" },
  { value: " (+242) Republic of the Congo", code: "CG", dial_code: "+242" },
  { value: " (+262) Reunion", code: "RE", dial_code: "+262" },
  { value: " (+40) Romania", code: "RO", dial_code: "+40" },
  { value: " (+7) Russia", code: "RU", dial_code: "+7" },
  { value: " (+250) Rwanda", code: "RW", dial_code: "+250" },
  { value: " (+590) Saint Barthelemy", code: "BL", dial_code: "+590" },
  { value: " (+290) Saint Helena", code: "SH", dial_code: "+290" },
  { value: " (+1-869) Saint Kitts and Nevis", code: "KN", dial_code: "+1-869" },
  { value: " (+1-758) Saint Lucia", code: "LC", dial_code: "+1-758" },
  { value: " (+590) Saint Martin", code: "MF", dial_code: "+590" },
  { value: " (+508) Saint Pierre and Miquelon", code: "PM", dial_code: "+508" },
  { value: " (+1-784) Saint Vincent and the Grenadines", code: "VC", dial_code: "+1-784" },
  { value: " (+685) Samoa", code: "WS", dial_code: "+685" },
  { value: " (+378) San Marino", code: "SM", dial_code: "+378" },
  { value: " (+239) Sao Tome and Principe", code: "ST", dial_code: "+239" },
  { value: " (+966) Saudi Arabia", code: "SA", dial_code: "+966" },
  { value: " (+221) Senegal", code: "SN", dial_code: "+221" },
  { value: " (+381) Serbia", code: "RS", dial_code: "+381" },
  { value: " (+248) Seychelles", code: "SC", dial_code: "+248" },
  { value: " (+232) Sierra Leone", code: "SL", dial_code: "+232" },
  { value: " (+65) Singapore", code: "SG", dial_code: "+65" },
  { value: " (+1-721) Sint Maarten", code: "SX", dial_code: "+1-721" },
  { value: " (+421) Slovakia", code: "SK", dial_code: "+421" },
  { value: " (+386) Slovenia", code: "SI", dial_code: "+386" },
  { value: " (+677) Solomon Islands", code: "SB", dial_code: "+677" },
  { value: " (+252) Somalia", code: "SO", dial_code: "+252" },
  { value: " (+27) South Africa", code: "ZA", dial_code: "+27" },
  { value: " (+82) South Korea", code: "KR", dial_code: "+82" },
  { value: " (+211) South Sudan", code: "SS", dial_code: "+211" },
  { value: " (+34) Spain", code: "ES", dial_code: "+34" },
  { value: " (+94) Sri Lanka", code: "LK", dial_code: "+94" },
  { value: " (+249) Sudan", code: "SD", dial_code: "+249" },
  { value: " (+597) Suriname", code: "SR", dial_code: "+597" },
  { value: " (+47) Svalbard and Jan Mayen", code: "SJ", dial_code: "+47" },
  { value: " (+268) Swaziland", code: "SZ", dial_code: "+268" },
  { value: " (+46) Sweden", code: "SE", dial_code: "+46" },
  { value: " (+41) Switzerland", code: "CH", dial_code: "+41" },
  { value: " (+963) Syria", code: "SY", dial_code: "+963" },
  { value: " (+886) Taiwan", code: "TW", dial_code: "+886" },
  { value: " (+992) Tajikistan", code: "TJ", dial_code: "+992" },
  { value: " (+255) Tanzania", code: "TZ", dial_code: "+255" },
  { value: " (+66) Thailand", code: "TH", dial_code: "+66" },
  { value: " (+228) Togo", code: "TG", dial_code: "+228" },
  { value: " (+690) Tokelau", code: "TK", dial_code: "+690" },
  { value: " (+676) Tonga", code: "TO", dial_code: "+676" },
  { value: " (+1-868) Trinidad and Tobago", code: "TT", dial_code: "+1-868" },
  { value: " (+216) Tunisia", code: "TN", dial_code: "+216" },
  { value: " (+90) Turkey", code: "TR", dial_code: "+90" },
  { value: " (+993) Turkmenistan", code: "TM", dial_code: "+993" },
  { value: " (+1-649) Turks and Caicos Islands", code: "TC", dial_code: "+1-649" },
  { value: " (+688) Tuvalu", code: "TV", dial_code: "+688" },
  { value: " (+1-340) U.S. Virgin Islands", code: "VI", dial_code: "+1-340" },
  { value: " (+256) Uganda", code: "UG", dial_code: "+256" },
  { value: " (+380) Ukraine", code: "UA", dial_code: "+380" },
  { value: " (+971) United Arab Emirates", code: "AE", dial_code: "+971" },
  { value: " (+44) United Kingdom", code: "GB", dial_code: "+44" },
  { value: " (+1) United States", code: "US", dial_code: "+1" },
  { value: " (+598) Uruguay", code: "UY", dial_code: "+598" },
  { value: " (+998) Uzbekistan", code: "UZ", dial_code: "+998" },
  { value: " (+678) Vanuatu", code: "VU", dial_code: "+678" },
  { value: " (+379) Vatican", code: "VA", dial_code: "+379" },
  { value: " (+58) Venezuela", code: "VE", dial_code: "+58" },
  { value: " (+84) Vietnam", code: "VN", dial_code: "+84" },
  { value: " (+681) Wallis and Futuna", code: "WF", dial_code: "+681" },
  { value: " (+212) Western Sahara", code: "EH", dial_code: "+212" },
  { value: " (+967) Yemen", code: "YE", dial_code: "+967" },
  { value: " (+260) Zambia", code: "ZM", dial_code: "+260" },
  { value: " (+263) Zimbabwe", code: "ZW", dial_code: "+263" }
]

