export const ProductCodeScheme = [
  {schemeCode: 'OPEGE', name: 'Edge Savings', schemeType: 'SBA'},
  {schemeCode: 'ON001', name: 'Natives', schemeType: 'SBA'},
  {schemeCode: 'ON002', name: 'Natives', schemeType: 'SBA'},
  {schemeCode: 'ON003', name: 'Natives', schemeType: 'SBA'},
  {schemeCode: 'OO001', name: 'One23', schemeType: 'SBA'},
  {schemeCode: 'OO002', name: 'One23', schemeType: 'SBA'},
  {schemeCode: 'OO003', name: 'One23', schemeType: 'SBA'},
  {schemeCode: 'OU001', name: 'One23 Ultra', schemeType: 'SBA'},
  {schemeCode: 'OU002', name: 'One23 Ultra', schemeType: 'SBA'},
  {schemeCode: 'OU003', name: 'One23 Ultra', schemeType: 'SBA'},
  {schemeCode: 'OW001', name: 'Sage Savings', schemeType: 'SBA'},
  {schemeCode: 'OW002', name: 'Sage Savings', schemeType: 'SBA'},
  {schemeCode: 'OW003', name: 'Sage Savings', schemeType: 'SBA'},
  {schemeCode: 'SB001', name: 'Savings', schemeType: 'SBA'},
  {schemeCode: 'SB02', name: 'Savings', schemeType: 'SBA'},
  {schemeCode: 'SB03', name: 'Savings', schemeType: 'SBA'},
  {schemeCode: 'SB003', name: 'Savings', schemeType: 'SBA'},
  {schemeCode: 'SB004', name: 'Savings', schemeType: 'SBA'},
  {schemeCode: 'AC003', name: 'Ace Classic', schemeType: 'ODA'},
  {schemeCode: 'AM003', name: 'Ace Main', schemeType: 'ODA'},
  {schemeCode: 'AR003', name: 'Ace Royal', schemeType: 'ODA'},
  {schemeCode: 'OAZ03', name: 'Avanzar Individual', schemeType: 'ODA'},
  {schemeCode: 'OV003', name: 'Avanzar Biz', schemeType: 'ODA'},
  {schemeCode: 'OBS03', name: 'Business Starter', schemeType: 'ODA'},
  {schemeCode: 'OBM03', name: 'Business Mini', schemeType: 'ODA'},
  {schemeCode: 'OBD03', name: 'Business Midi', schemeType: 'ODA'},
  {schemeCode: 'OBX03', name: 'Business Maxi', schemeType: 'ODA'},
  {schemeCode: 'OD001', name: 'Current', schemeType: 'ODA'},
  {schemeCode: 'OD002', name: 'Current', schemeType: 'ODA'},
  {schemeCode: 'OD003', name: 'Current', schemeType: 'ODA'},
  {schemeCode: 'OD004', name: 'Current', schemeType: 'ODA'},
  {schemeCode: 'OD005', name: 'Current Salary Deposit', schemeType: 'ODA'},
  {schemeCode: 'OPEGD', name: 'Edge Current', schemeType: 'ODA'},
  {schemeCode: 'OPOSI', name: 'Street Agent Individual', schemeType: 'ODA'},
  {schemeCode: 'OPOSB', name: 'Street Agent Business', schemeType: 'ODA'},
  {schemeCode: 'OZ003', name: 'Sage Current', schemeType: 'ODA'},
  {schemeCode: 'OPPRM', name: 'Premium', schemeType: 'LAA'},
  {schemeCode: 'OPPRL', name: 'Premium Lite', schemeType: 'LAA'},
  {schemeCode: 'OPAVZ', name: 'Premium Avanzar Individual', schemeType: 'LAA'},
  {schemeCode: 'OPAVB', name: 'Premium Avanzar Biz', schemeType: 'LAA'},
];
